### ISSUE TITLE
Release version 0.0.1 exe is detected as malware by Windows Defender

### ISSUE THREAD

**Issue by itweeb** [HarukaMa/palworld-xgp-import#2]
<img width="373" alt="Screenshot 2024-01-31 164934" src="https://github.com/HarukaMa/palworld-xgp-import/assets/11187457/efb4148c-92bb-4964-8bf6-6e9203462b14">

**Comment by HarukaMa** [comment]
![image](https://github.com/HarukaMa/palworld-xgp-import/assets/861659/31bb0f16-0e9c-4df8-93bb-56b0c36806fb)

I don't have other ways to pack everything into one file as all common methods will be flagged by various antivirus providers. Blame the people who abuse those packing tools and the antivirus for their incompetence.

**Comment by itweeb** [comment]
> ![image](https://private-user-images.githubusercontent.com/861659/301335023-31bb0f16-0e9c-4df8-93bb-56b0c36806fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NTMwNzgsIm5iZiI6MTcwNzk1Mjc3OCwicGF0aCI6Ii84NjE2NTkvMzAxMzM1MDIzLTMxYmIwZjE2LTBlOWMtNGRmOC05M2JiLTU2YjBjMzY4MDZmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQyMzE5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzA1ZTY5YTdjOTZhMjZjZGRhN2QwNzE5M2MzMDdmNTQzYTNmNjFjYzE2YzBjZmY4ODhmMWY1Nzk0ZjIxYzM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kl4yHjoxRCmlpw-Bycpqa8uhgjGBu6h03RAhQ2uEmDU)
> 
> I don't have other ways to pack everything into one file as all common methods will be flagged by various antivirus providers. Blame the people who abuse those packing tools and the antivirus for their incompetence.

I seriously doubted it was legit given the program is literally just a python script. I just reported it since I didn't see it mentioned elsewhere. Thanks for the response.

**Comment by HarukaMa** [comment]
Just for the reference, I think https://github.com/Z1ni/XGP-save-extractor also has the similar issue. If that one is not getting flagged then I'll need to change something on my end.
