### ISSUE TITLE
Error: Save File Exists

### ISSUE THREAD

**Issue by Chrisgrx5** [HarukaMa/palworld-xgp-import#3]
Hi. Not sure what I am doing wrong. When I try to convert my Steam save to go back on to PC GPass it loads all the data then says there is a save file already exists

**Comment by silpherion** [comment]
Hi @Chrisgrx5 how did you fix this issue? I'm having the same issue

**Comment by Chrisgrx5** [comment]
> Hi @Chrisgrx5 how did you fix this issue? I'm having the same issue

Hi. Rename the folder with long digits to something else. Even by changing 2/3 digits will do the trick

**Comment by silpherion** [comment]
> > Hi @Chrisgrx5 how did you fix this issue? I'm having the same issue
> 
> Hi. Rename the folder with long digits to something else. Even by changing 2/3 digits will do the trick

thank you so much! You saved me so much time trying to figure this out.
