### ISSUE TITLE
World not showing

### ISSUE THREAD

**Issue by Nuggeti** [HarukaMa/palworld-xgp-import#4]
My friend was having trouble hosting the world himself so we decided to transfer it to me. We play on gamepass version so to do it I converted the save folder to the steam version with xpg save extractor, recovered the character that went missing, and then used the app to import the sabe to xbox version again. But now when I open the game the world is not showing, I tested another save online and it worked fine and our save was working fine in steam version too. What it could be the issue?

**Comment by Nuggeti** [comment]
Seems like it has a problem with save with more than one player

**Comment by HarukaMa** [comment]
Probably cloud syncing related. Unfortunately I'm not sure how to detect the cloud sync state. Try importing the save again to see if it already exists in the container.

**Comment by Nuggeti** [comment]
I think I nailed it. I needed to use an older version of our save. For some reason the newer was corrupted or something like that.

**Comment by Abyss-W4tcher** [comment]
Hi, I am also trying to transfer an XGP palworld save from another computer/account to my PC. We converted the save file with XGP-Extractor and sent it to my computer. Then, I imported it back with this tool, but even after waiting a bit I do not see the world showing in my saves. 

Did I miss a step in the procedure ? 

Thanks !
