### ISSUE TITLE
World not showing up

### ISSUE THREAD

**Issue by Pyrolaxian** [HarukaMa/palworld-xgp-import#6]
Error occuring when putting world in, it imports perfectly fine but world does not show up at all and works fine when I delete all data and let xbox cloud sync it

**Comment by Pyrolaxian** [comment]
Closing the issue, found a fix for anyone having a struggle with version mismatch etc...

Import the save file WHEN Palworld is open

**Comment by guerrillian** [comment]
can you teach us how to use it? I couldn't manage

**Comment by Pyrolaxian** [comment]
> can you teach us how to use it? I couldn't manage

Make sure the name of your save file you exported originally is renamed, or it will already exist in your Xbox cloud and will return an error saying it already exists. 

For example, my folder was called "1CF68C534659F73A3D3841BE8B615C59" which returns an error. Simply rename the folder, either change the name completely or add/remove a couple letters or numbers.

Once done, open Palworld on Xbox and wait until your cloud has synced, once done you can then drag your folder into the .exe and it will add the save file.

Reboot Palworld and see if the world has appeared, if not try repeating again with administrator on the .exe

If it has shown up, make sure you let the cloud sync once closing before trying to access on another Xbox device, if you are playing on your PC version then go ahead and play the world

**Comment by guerrillian** [comment]
but where I should put the exe? In the saves folder?

**Comment by Pyrolaxian** [comment]
> but where I should put the exe? In the saves folder?

Shouldn't matter, I kept mine in my downloads folder

If you're having issues, keep the save file and the exe in the same folder

**Comment by guerrillian** [comment]
I extracted the folder, it came in .rar, I edited what I want, and I'm trying to convert the .rar back to the save files, it is not working here

![image](https://github.com/HarukaMa/palworld-xgp-import/assets/128705907/327929be-5cac-484c-a334-bbf3327188c3)

**Comment by Pyrolaxian** [comment]
> I extracted the folder, it came in .rar, I edited what I want, and I'm trying to convert the .rar back to the save files, it is not working here

Are you trying to import the .rar file?
Needs to be the folder, it should just be a singular folder with a long string of text

**Comment by guerrillian** [comment]
yes i'm lol

The extractor creates the folder and a .sav file, I dont need the .sav file?
![image](https://github.com/HarukaMa/palworld-xgp-import/assets/128705907/619b7b8a-816b-4cdd-82bf-929218926bbf)

**Comment by guerrillian** [comment]
thank you very much, it worked :)

**Comment by Pyrolaxian** [comment]
> thank you very much, it worked :)

Glad it worked, was just about to reply, yeah you only need the folder
