### ISSUE TITLE
doesnt seem to work for me

### ISSUE THREAD

**Issue by Shadowuser555** [HarukaMa/palworld-xgp-import#8]
downloaded, added to trusted files, dragged and dropped a steam save file from nexus mods and the tool does absolutely nothing upon "pressing a key" and closes right after dragging the steam save file onto your tool. what am i doing wrong? does your tool need to be in the same location as my wgs folder? not much to go off your READ ME to be fair. alot of people assume everyone knows exactly where files should be placed upon downloading like everyone is a computer file expert... i just wanna use someones save file im tired of mine being deleted.

**Comment by Pyrolaxian** [comment]
Make sure the save file has a parent folder.

E.g

-> Parent Folder
---> Save data (couple of folders)

Make sure that the game is open on Xbox game pass  while importing the save, it must be the PC version open however the save will work on any copy as long as the version remains consistent.
